package org.telegram.galacticMiniatures.bot.enums;

public enum BotState {
  WORKING,
  FILLING_FULL_NAME,
  FILLING_TOWN,
  FILLING_ADDRESS,
  FILLING_POST_INDEX,
  FILLING_CONTACTS,
  ADMIN_PROMOTE,
  ADMIN_DEMOTE,
  MODERATOR_PROMOTE,
  MODERATOR_DEMOTE,
  ADDING_USER_ORDER_MESSAGE,
  ADDING_ADMIN_SCROLLER_MESSAGE,
  ADDING_USER_SCROLLER_MESSAGE,
  ADDING_CHAT_MESSAGE
}