bot:
  name: ${MYBOTNAME}
  token: ${MYBOTTOKEN}
etsy:
  shopId: ${ETSY_SHOP_ID}
  apiKey: ${ETSY_API_KEY}
schedule:
  clearCache: PT2H
  parsePeriod: PT6H
  announcementPeriod: PT1M
  entityExpirationTime: 20000
spring:
  datasource:
    url: jdbc:${DATABASE_URL:postgresql://localhost:5432/mybot_db?rewriteBatchedStatements=true}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database : postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        generate_statistics: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20
          fetch_size: 20
server:
  port: ${PORT:8080}